//! ISSO 82.1 (7e druk) chapter 9: space heating in the basic survey.
//!
//! - No generator present during a renovation: the previous one, else a
//!   conventional boiler (p. 107).
//! - Pilot flame unknown: with pilot flame (table 9.3, p. 108); a hydrogen
//!   boiler counts as HR-107 on natural gas (p. 108).
//! - Heat-pump water source unknown: ground; individual surface water:
//!   ground (table 9.6, p. 110–111).
//! - Design temperature class unknown: table 9.9 (p. 114, erratum §4).
//! - Several emitters: surface heating before radiators/convectors before
//!   air heating (p. 123–124).
//! - Hydronic balancing unknown: not balanced (table 9.10, p. 116).
//! - Emission control unknown: other/unknown (table 9.17, p. 124).
//! - Pipe insulation unknown: not insulated (table 9.12, p. 118); the heat
//!   meter of table 9.16a (p. 122) applies to collective installations
//!   only, so individual systems have none; pumps unknown: forfait
//!   (table 9.11, p. 117).
//! - Ground or groundwater source without solar regeneration: c_source
//!   1,0 (p. 110; NTA table 9.27 footnote a).
//! - Exhaust-air heat pump: a second generator is required (WD 2025
//!   p. 43); without `additionalGenerators` it is rejected.
//! - Several generators (§9.3.2, p. 112–113): every unequal generator is
//!   entered with its nominal power (table 9.7); the preference follows the
//!   p. 112 order (exhaust-air heat pumps, other heat pumps, CHP, biomass,
//!   external heat, electric, gas/oil boilers). External heat of unknown
//!   power takes 50 % (table 9.7); an added preferred generator (§9.3.6)
//!   uses NTA 9.58/9.59.
//! - Collective installations (p. 106, 121–122): the connected usable area
//!   unknown → dwellings × the dwelling's area (p. 121); heat meters
//!   unknown → present (table 9.16a, p. 122); pipes forfait (table 9.14).
//! - Biomass annex R compliance unknown: not compliant (p. 111–112, 28).

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use super::Recorder;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BoilerType {
    Conventional,
    Vr,
    Hr100,
    Hr104,
    Hr107,
    /// Boiler on hydrogen: HR-107 on natural gas (p. 108).
    Hydrogen,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum HeatPumpSource {
    OutdoorAir,
    ExhaustAir,
    OutdoorAndExhaustAir,
    Ground,
    Groundwater,
    /// Individual systems: counts as ground (p. 111).
    SurfaceWater,
    /// Water-based source of unknown kind: ground (table 9.6).
    WaterBasedUnknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BiomassApplianceAnswer {
    FreestandingWoodStove,
    InsertStove,
    PelletStove,
    AccumulatingStove,
    CentralBoiler,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum HeatingGenerator {
    Boiler {
        #[serde(rename = "boilerType")]
        boiler_type: BoilerType,
        #[serde(default, rename = "pilotFlame")]
        pilot_flame: Option<bool>,
        #[serde(rename = "insideThermalBoundary")]
        inside_thermal_boundary: bool,
        #[serde(default, rename = "manufactureYear")]
        manufacture_year: Option<i32>,
        #[serde(default, rename = "installationYear")]
        installation_year: Option<i32>,
    },
    HeatPump {
        source: HeatPumpSource,
        /// Indoor air as the sink (air/air heat pump).
        #[serde(default, rename = "airSink")]
        air_sink: bool,
        /// Suitable for high temperatures (table 9.9).
        #[serde(default, rename = "highTemperature")]
        high_temperature: bool,
        #[serde(default, rename = "capacityKw")]
        capacity_kw: Option<f64>,
        /// Annex V c_source of a ground source regenerated by a solar
        /// system (ISSO 82.1 p. 110); `None`: no regeneration, 1,0.
        #[serde(default, rename = "sourceRegenerationFactor")]
        source_regeneration_factor: Option<f64>,
        /// Product data showing the table 9.5 (NTA table 9.28) COP values
        /// (ISSO 82.1 p. 109); passed to the kernel as
        /// `highEfficiencyEvidence`.
        #[serde(default, rename = "highEfficiencyEvidence")]
        high_efficiency_evidence: Option<Value>,
    },
    DistrictHeat,
    Electric {
        #[serde(rename = "connectedDevices")]
        connected_devices: u32,
    },
    Biomass {
        appliance: BiomassApplianceAnswer,
        #[serde(rename = "insideThermalBoundary")]
        inside_thermal_boundary: bool,
        #[serde(rename = "soleHeatingInServedRooms")]
        sole_heating_in_served_rooms: bool,
        /// Annex R compliance (ISSO 82.1 p. 111–112, "indien bekend");
        /// `None`: not compliant (conservative, p. 28).
        #[serde(default, rename = "annexRCompliant")]
        annex_r_compliant: Option<bool>,
    },
    /// Building CHP (NTA 9.6.6.1, table 9.31; ISSO table 9.7).
    Chp {
        /// Electrical power P_el, kW (table 9.31 row).
        #[serde(rename = "electricalPowerKw")]
        electrical_power_kw: f64,
        /// Thermal power, kW; unknown → table 9.7 rule of thumb on P_el
        /// by `engine`.
        #[serde(default, rename = "thermalPowerKw")]
        thermal_power_kw: Option<f64>,
        /// Table 9.7: gas engine (1,5), diesel engine (1,2) or micro
        /// turbine (2,5); unknown → gas engine.
        #[serde(default)]
        engine: Option<ChpEngine>,
        #[serde(default, rename = "manufactureYear")]
        manufacture_year: Option<i32>,
        /// HRe declaration for P_el ≤ 2 kW (table 9.31).
        #[serde(default, rename = "hreDeclared")]
        hre_declared: bool,
        /// LT operation demonstrated with design data (table 9.31 note a).
        #[serde(default, rename = "lowTemperature")]
        low_temperature: bool,
    },
    /// No generator present (renovation), previous one unknown.
    NonePresent,
}

/// Prime mover of a CHP for the table 9.7 rule of thumb.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ChpEngine {
    GasEngine,
    DieselEngine,
    MicroTurbine,
}

impl ChpEngine {
    /// Table 9.7 (ISSO 82.1 p. 113): thermal / electrical power.
    pub fn thermal_ratio(self) -> f64 {
        match self {
            Self::GasEngine => 1.5,
            Self::DieselEngine => 1.2,
            Self::MicroTurbine => 2.5,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Emitters {
    Radiators,
    LowTemperatureRadiators,
    FloorHeating,
    FloorHeatingAndRadiators,
    AirHeating,
    LocalHeaters,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ControlAnswer {
    RoomThermostat,
    CentralWithRadiatorValves,
    IndividualRoomControl,
    Unknown,
}

/// Table 9.9 classes (supply/return, °C).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum DesignClass {
    C45_40,
    C55_47,
    C70_50,
    C90_70,
}

impl DesignClass {
    fn supply_c(self) -> f64 {
        match self {
            Self::C45_40 => 45.0,
            Self::C55_47 => 55.0,
            Self::C70_50 => 70.0,
            Self::C90_70 => 90.0,
        }
    }

    /// Mean design emission temperature of the NTA table 9.14 class used
    /// for the distribution (`kernel`), so the boiler and the distribution
    /// describe the same circuit: 70/50 maps to 70/60 and takes 65 °C. Only
    /// the 50 °C threshold of the boiler forfait reads it, so the choice
    /// has no effect on the result.
    fn mean_c(self) -> f64 {
        match self {
            Self::C45_40 => 42.5,
            Self::C55_47 => 51.0,
            Self::C70_50 => 65.0,
            Self::C90_70 => 80.0,
        }
    }

    fn label(self) -> &'static str {
        match self {
            Self::C45_40 => "45/40",
            Self::C55_47 => "55/47",
            Self::C70_50 => "70/50",
            Self::C90_70 => "90/70",
        }
    }

    /// NTA table 9.14 class for the distribution; ISSO 70/50 has no NTA
    /// row and takes 70/60 (same design supply temperature).
    fn kernel(self) -> &'static str {
        match self {
            Self::C45_40 => "45_40",
            Self::C55_47 => "55_47",
            Self::C70_50 => "70_60",
            Self::C90_70 => "90_70",
        }
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SurveyHeating {
    pub generator: HeatingGenerator,
    pub emitters: Emitters,
    #[serde(default)]
    pub design_class: Option<DesignClass>,
    /// Controlled declaration (gecontroleerde verklaring) that a heat pump
    /// delivers a supply temperature above 70 °C; required when an explicit
    /// class above 70 °C applies to a heat pump (table 9.9 footnotes 9–11,
    /// erratum §4).
    #[serde(default)]
    pub heat_pump_above_70_declaration: Option<String>,
    /// `None`: not determinable.
    #[serde(default)]
    pub balanced: Option<bool>,
    pub control: ControlAnswer,
    /// Pipes in unheated spaces (afb. 9.1); `None`: spaces not inspectable
    /// and unknown whether pipes run there → present, forfait length.
    #[serde(default)]
    pub unheated_pipes: Option<UnheatedPipesAnswer>,
    /// Storeys served by the distribution (9.37).
    #[serde(default = "one")]
    pub storeys: u32,
    /// Nominal power of the main generator (table 9.7), kW; required with
    /// `additionalGenerators`.
    #[serde(default)]
    pub nominal_power_kw: Option<f64>,
    /// Further unequal generators on the same distribution (§9.3.2).
    #[serde(default)]
    pub additional_generators: Vec<AdditionalHeatingGenerator>,
    /// §9.3.6: a preferred generator added after delivery (renovation).
    #[serde(default)]
    pub added_preferred_generator: bool,
    /// Collective installation serving several dwellings (p. 106, 121).
    #[serde(default)]
    pub collective: Option<CollectiveHeating>,
    /// ISSO 82.1 table 9.16b / 75.1: the air-heating type with emitters
    /// `air_heating`.
    #[serde(default)]
    pub air_heating: Option<AirHeatingAnswer>,
    pub source_reference: String,
}

/// ISSO table 9.16b: direct or indirect air heaters, or air heating
/// through the air-handling unit (then entered with the ventilation).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum AirHeatingAnswer {
    Direct {
        /// Radial recirculation fan; `None` unknown (radial).
        #[serde(default, rename = "radialFan")]
        radial_fan: Option<bool>,
        /// Number of air heaters (table 9.16b).
        #[serde(default)]
        count: Option<u32>,
    },
    Indirect {
        #[serde(default, rename = "roomHeightAbove8M")]
        room_height_above_8_m: Option<bool>,
        #[serde(default, rename = "warmAirReturn")]
        warm_air_return: Option<bool>,
        #[serde(default, rename = "ecMotor")]
        ec_motor: Option<bool>,
        #[serde(default)]
        count: Option<u32>,
    },
    ViaAirHandlingUnit,
}

/// One further generator with its table 9.7 nominal power.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AdditionalHeatingGenerator {
    pub generator: HeatingGenerator,
    #[serde(default)]
    pub nominal_power_kw: Option<f64>,
}

/// A collective heating installation (ISSO 82.1 p. 106, 121–122).
#[derive(Debug, Clone, Default, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CollectiveHeating {
    /// Usable area of the building on the installation, m².
    #[serde(default)]
    pub connected_usable_area_m2: Option<f64>,
    /// Dwellings on the installation, for the p. 121 rule.
    #[serde(default)]
    pub connected_dwellings: Option<u32>,
    /// Storeys on the installation (9.37); `None`: the dwelling's storeys.
    #[serde(default)]
    pub connected_storeys: Option<u32>,
    /// Table 9.16a: `None` unknown → present.
    #[serde(default)]
    pub heat_meters_present: Option<bool>,
}

fn one() -> u32 {
    1
}

/// Table 9.9 when the class is unknown.
pub fn design_class(
    emitters: Emitters,
    generator: &HeatingGenerator,
    recorder: &mut Recorder,
) -> DesignClass {
    let class = match (emitters, generator) {
        (Emitters::FloorHeating, _) => DesignClass::C45_40,
        (Emitters::LowTemperatureRadiators, _) => DesignClass::C55_47,
        (
            _,
            HeatingGenerator::HeatPump {
                high_temperature: false,
                ..
            },
        ) => DesignClass::C55_47,
        (
            _,
            HeatingGenerator::HeatPump {
                high_temperature: true,
                ..
            },
        ) => DesignClass::C70_50,
        _ => DesignClass::C90_70,
    };
    recorder.record(
        "design_temperature_class_unknown",
        "heating.designClass",
        class.label().into(),
        "ISSO 82.1 p. 114 (table 9.9, erratum §4)",
    );
    class
}

/// Kernel fragments for the space-heating chain.
pub struct DerivedHeating {
    pub emission: Value,
    pub generator: Value,
    pub distribution_system: Option<Value>,
    pub heat_pump_renewable: Option<Value>,
    /// Water-based emission (a distribution system exists).
    pub hydronic: bool,
    /// NTA table 9.14 class of the distribution.
    pub design_class: &'static str,
}

/// Pipes in unheated spaces (afb. 9.1, p. 120).
#[derive(Debug, Clone, Copy, PartialEq, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum UnheatedPipesAnswer {
    /// No central-heating pipes or manifolds in unheated spaces.
    Absent,
    /// Present; `lengthM` the supply plus return length there, else forfait.
    Present {
        #[serde(default, rename = "lengthM")]
        length_m: Option<f64>,
    },
}

pub fn derive_heating(
    heating: &SurveyHeating,
    construction_year: i32,
    recorder: &mut Recorder,
) -> DerivedHeating {
    let reference = heating.source_reference.as_str();
    let generator = match &heating.generator {
        HeatingGenerator::NonePresent => {
            recorder.record(
                "no_generator_conventional_boiler",
                "heating.generator",
                "conventional boiler".into(),
                "ISSO 82.1 p. 107",
            );
            HeatingGenerator::Boiler {
                boiler_type: BoilerType::Conventional,
                pilot_flame: None,
                inside_thermal_boundary: true,
                manufacture_year: None,
                installation_year: None,
            }
        }
        other => other.clone(),
    };
    // Table 9.9 (p. 114): with several generators a non-heat-pump one
    // decides the class ("als opwekker geen warmtepomp is").
    let class_generator = std::iter::once(&generator)
        .chain(
            heating
                .additional_generators
                .iter()
                .map(|item| &item.generator),
        )
        .find(|item| !is_heat_pump(item))
        .unwrap_or(&generator);
    let design = heating
        .design_class
        .unwrap_or_else(|| design_class(heating.emitters, class_generator, recorder));
    let (system, hydronic) = match heating.emitters {
        Emitters::Radiators | Emitters::LowTemperatureRadiators => {
            ("radiators_or_convectors", true)
        }
        Emitters::FloorHeating => ("floor_heating", true),
        Emitters::FloorHeatingAndRadiators => {
            recorder.record(
                "several_emitters_surface_heating_first",
                "heating.emitters",
                "floor_heating".into(),
                "ISSO 82.1 p. 123–124",
            );
            ("floor_heating", true)
        }
        Emitters::AirHeating => ("air_heating", false),
        Emitters::LocalHeaters => ("local_heater", false),
    };
    let balancing = if !hydronic {
        "not_applicable"
    } else {
        match heating.balanced {
            Some(true) => "static",
            Some(false) => "none_or_unknown",
            None => {
                recorder.record(
                    "hydronic_balancing_unknown_none",
                    "heating.balanced",
                    "none_or_unknown".into(),
                    "ISSO 82.1 p. 116 (table 9.10)",
                );
                "none_or_unknown"
            }
        }
    };
    let control = match heating.control {
        ControlAnswer::RoomThermostat => "main_room_thermostat",
        ControlAnswer::CentralWithRadiatorValves => "central_with_room_valves",
        ControlAnswer::IndividualRoomControl => "individual_room_thermostats",
        ControlAnswer::Unknown => {
            recorder.record(
                "emission_control_unknown_other",
                "heating.control",
                "other_or_unknown".into(),
                "ISSO 82.1 p. 124 (table 9.17)",
            );
            "other_or_unknown"
        }
    };
    let mut emission = json!({
        "system": system, "balancing": balancing, "control": control,
        "sourceReference": format!("{reference}; basisopname"),
    });
    // Table 9.16b → NTA 9.23 (tables 9.12/9.13); unknown properties take the
    // highest factor, as the kernel does for a missing value.
    match (heating.emitters, heating.air_heating) {
        (Emitters::AirHeating, Some(answer)) => {
            let kind = match answer {
                AirHeatingAnswer::Direct { radial_fan, .. } => {
                    if radial_fan.is_none() {
                        recorder.record(
                            "air_heater_fan_unknown_radial",
                            "heating.airHeating.radialFan",
                            "radial recirculation fan".into(),
                            "ISSO 82.1 p. 123 (table 9.16b)",
                        );
                    }
                    Some(json!({"kind": "direct", "radialFan": radial_fan}))
                }
                AirHeatingAnswer::Indirect {
                    room_height_above_8_m,
                    warm_air_return,
                    ec_motor,
                    ..
                } => {
                    if room_height_above_8_m.is_none()
                        || warm_air_return.is_none()
                        || ec_motor.is_none()
                    {
                        recorder.record(
                            "air_heater_indirect_unknown_highest",
                            "heating.airHeating",
                            "AC fans, room higher than 8 m, without warm-air return".into(),
                            "ISSO 82.1 p. 123 (table 9.16b)",
                        );
                    }
                    Some(json!({
                        "kind": "indirect",
                        "roomHeightAbove8M": room_height_above_8_m,
                        "warmAirReturn": warm_air_return,
                        "ecMotor": ec_motor,
                    }))
                }
                // The AHU fans count in chapter 11.
                AirHeatingAnswer::ViaAirHandlingUnit => None,
            };
            if let Some(kind) = kind {
                emission["airHeaters"] = json!({
                    "kind": kind,
                    "sourceReference": format!("{reference}; ISSO table 9.16b"),
                });
            }
        }
        (Emitters::AirHeating, None) => {
            recorder.record(
                "air_heating_type_unknown",
                "heating.airHeating",
                "not applicable: no air-heater fan energy".into(),
                "ISSO 82.1 p. 123 (table 9.16b)",
            );
        }
        (_, Some(_)) => recorder.issue(
            "air_heating_requires_air_heating_emitters",
            "heating.airHeating",
        ),
        (_, None) => {}
    }

    // Table 9.9 footnotes 9–11 as corrected by erratum §4: a heat pump
    // with a supply temperature above 70 °C needs a controlled declaration.
    // Only an explicit class can exceed 70 °C for a heat pump; the defaults
    // above stop at 70/50.
    let heat_pump_present = std::iter::once(&generator)
        .chain(
            heating
                .additional_generators
                .iter()
                .map(|item| &item.generator),
        )
        .any(is_heat_pump);
    if heat_pump_present
        && heating
            .design_class
            .is_some_and(|class| class.supply_c() > 70.0)
        && heating
            .heat_pump_above_70_declaration
            .as_deref()
            .map_or(true, |value| value.trim().is_empty())
    {
        recorder.issue(
            "heat_pump_above_70_requires_declaration",
            "heating.heatPumpAbove70Declaration",
        );
    }

    let collective = heating.collective.is_some();
    // Table 9.9 per generator (p. 114): with several generators a heat
    // pump keeps its own class (footnote 8: a hybrid heat pump is not
    // high-temperature by default); the distribution takes the highest.
    let several = !heating.additional_generators.is_empty();
    let generator_design = |item: &HeatingGenerator, recorder: &mut Recorder| {
        if several && is_heat_pump(item) && heating.design_class.is_none() {
            design_class(heating.emitters, item, recorder)
        } else {
            design
        }
    };
    let main_design = generator_design(&generator, recorder);
    let main = convert_generator(
        &generator,
        main_design,
        hydronic,
        collective,
        heating.nominal_power_kw,
        "opwekker-1",
        reference,
        construction_year,
        recorder,
    );
    let mut needs_pump = main.needs_pump;
    let mut heat_pump_renewable = main.heat_pump_renewable;
    let generator_value = if heating.additional_generators.is_empty() {
        if is_exhaust_air(&generator) {
            // WD 2025 p. 43: an exhaust-air heat pump needs a second
            // generator.
            recorder.issue(
                "exhaust_air_heat_pump_second_generator_required",
                "heating.generator.source",
            );
        }
        main.value
    } else {
        let mut parts = vec![(generator.clone(), heating.nominal_power_kw, main.value)];
        for (index, extra) in heating.additional_generators.iter().enumerate() {
            let generator = match &extra.generator {
                HeatingGenerator::NonePresent => {
                    recorder.issue(
                        "additional_generator_missing",
                        format!("heating.additionalGenerators[{index}].generator"),
                    );
                    continue;
                }
                other => other.clone(),
            };
            let extra_design = generator_design(&generator, recorder);
            let converted = convert_generator(
                &generator,
                extra_design,
                hydronic,
                collective,
                extra.nominal_power_kw,
                &format!("opwekker-{}", index + 2),
                reference,
                construction_year,
                recorder,
            );
            needs_pump |= converted.needs_pump;
            heat_pump_renewable = heat_pump_renewable.or(converted.heat_pump_renewable);
            parts.push((generator, extra.nominal_power_kw, converted.value));
        }
        multiple_generators(
            parts,
            heating.added_preferred_generator,
            reference,
            recorder,
        )
    };
    let distribution_system = needs_pump.then(|| {
        recorder.record(
            "pipe_insulation_unknown_uninsulated",
            "heating.distribution",
            "uninsulated".into(),
            "ISSO 82.1 p. 118 (table 9.12)",
        );
        recorder.record(
            "pump_unknown_forfait",
            "heating.distribution.pump",
            "forfait (9.41–9.51)".into(),
            "ISSO 82.1 p. 117 (table 9.11)",
        );
        match &heating.collective {
            Some(collective) => {
                // Table 9.16a (p. 122): heat meters unknown → present.
                let meters = collective.heat_meters_present.unwrap_or_else(|| {
                    recorder.record(
                        "heat_meters_unknown_present",
                        "heating.collective.heatMetersPresent",
                        "present".into(),
                        "ISSO 82.1 p. 122 (table 9.16a)",
                    );
                    true
                });
                json!({
                    "designTemperatureClass": design.kernel(),
                    "installation": "collective",
                    "usageFunction": "residential",
                    "connectedStoreys": collective.connected_storeys.unwrap_or(heating.storeys).max(1),
                    "pipeTransmittance": {"method": "forfait", "insulation": {"state": "uninsulated"}},
                    "valvesInsulated": false,
                    "pump": {"method": "calculated", "heatMeterPresent": meters, "sourceReference": "basisopname forfait; collective installation"},
                    "sourceReference": format!("{reference}; basisopname"),
                })
            }
            None => json!({
                "designTemperatureClass": design.kernel(),
                "installation": "individual",
                "usageFunction": "residential",
                "connectedStoreys": heating.storeys.max(1),
                "pipeTransmittance": {"method": "forfait", "insulation": {"state": "uninsulated"}},
                "valvesInsulated": false,
                // Table 9.16a (heat meter unknown: present) covers
                // collective installations only.
                "pump": {"method": "calculated", "heatMeterPresent": false, "sourceReference": "basisopname forfait; individual installation without heat meter"},
                "sourceReference": format!("{reference}; basisopname"),
            }),
        }
    });
    DerivedHeating {
        emission,
        generator: generator_value,
        distribution_system,
        heat_pump_renewable,
        hydronic,
        design_class: design.kernel(),
    }
}

/// NTA 9.2 f_gebouw;si;H of a collective installation: the connected usable
/// area, or dwellings × the dwelling's area (ISSO 82.1 p. 121).
pub fn collective_connection(
    heating: &SurveyHeating,
    dwelling_area_m2: f64,
    recorder: &mut Recorder,
) -> Option<Value> {
    let collective = heating.collective.as_ref()?;
    let area = match (
        collective.connected_usable_area_m2,
        collective.connected_dwellings,
    ) {
        (Some(area), _) => area,
        (None, Some(dwellings)) => {
            let area = f64::from(dwellings) * dwelling_area_m2;
            recorder.record(
                "collective_area_dwellings_times_area",
                "heating.collective.connectedUsableAreaM2",
                format!("{dwellings} × {dwelling_area_m2} m² = {area} m²"),
                "ISSO 82.1 p. 121",
            );
            area
        }
        (None, None) => {
            recorder.issue(
                "collective_connected_area_required",
                "heating.collective.connectedUsableAreaM2",
            );
            return None;
        }
    };
    if !(area.is_finite() && area >= dwelling_area_m2) {
        recorder.issue(
            "collective_connected_area_invalid",
            "heating.collective.connectedUsableAreaM2",
        );
        return None;
    }
    Some(json!({
        "connectedUsableAreaM2": area,
        "sourceReference": format!("{}; ISSO 82.1 p. 121", heating.source_reference),
    }))
}

/// Afb. 9.1 (p. 120): heating pipes in unheated spaces turn the
/// distribution into the calculated route (9.26–9.40) with the 15 %
/// forfait share of 9.26 unless a length is given.
pub fn apply_unheated_pipes(
    heating: &SurveyHeating,
    derived: &mut DerivedHeating,
    unheated_spaces_present: bool,
    recorder: &mut Recorder,
) -> Option<Value> {
    if !derived.hydronic || !unheated_spaces_present {
        return None;
    }
    let length = match heating.unheated_pipes {
        Some(UnheatedPipesAnswer::Absent) => return None,
        Some(UnheatedPipesAnswer::Present { length_m }) => length_m,
        None => {
            recorder.record(
                "unheated_pipes_unknown_present",
                "heating.unheatedPipes",
                "present, forfait length (15 % of L, 9.26)".into(),
                "ISSO 82.1 p. 120 (afb. 9.1), p. 121 (table 9.14)",
            );
            None
        }
    };
    let reference = heating.source_reference.as_str();
    let mut system = derived.distribution_system.take().unwrap_or_else(|| {
        recorder.record(
            "pipe_insulation_unknown_uninsulated",
            "heating.distribution",
            "uninsulated".into(),
            "ISSO 82.1 p. 118 (table 9.12)",
        );
        json!({
            "designTemperatureClass": derived.design_class,
            "installation": "individual",
            "usageFunction": "residential",
            "connectedStoreys": heating.storeys.max(1),
            "pipeTransmittance": {"method": "forfait", "insulation": {"state": "uninsulated"}},
            "valvesInsulated": false,
            "pump": {"method": "included_in_generator_auxiliary"},
            "sourceReference": format!("{reference}; basisopname"),
        })
    });
    if let Some(length) = length {
        system["unheatedPipeLengthM"] = json!(length);
    }
    derived.distribution_system = Some(system);
    Some(json!({
        "method": "calculated",
        "sourceReference": format!("{reference}; basisopname: pipes in unheated spaces (afb. 9.1)"),
    }))
}

/// Table 9.7 (ISSO 82.1 p. 113, 75.1 equally): the thermal power of a
/// CHP; unknown → the rule of thumb on the electrical power: 1,5 for gas
/// engines, 1,2 for diesel engines and 2,5 for micro turbines (engine
/// unknown → gas engine).
fn chp_thermal_power(
    electrical: f64,
    thermal: Option<f64>,
    engine: Option<ChpEngine>,
    recorder: &mut Recorder,
) -> f64 {
    thermal.unwrap_or_else(|| {
        let engine = engine.unwrap_or_else(|| {
            recorder.record(
                "chp_engine_unknown_gas",
                "heating.generator.engine",
                "gas_engine".into(),
                "ISSO 82.1 p. 113 (table 9.7)",
            );
            ChpEngine::GasEngine
        });
        let ratio = engine.thermal_ratio();
        recorder.record(
            "chp_thermal_power_from_electrical",
            "heating.generator.thermalPowerKw",
            format!("{ratio} × {electrical} kW"),
            "ISSO 82.1 p. 113 (table 9.7)",
        );
        ratio * electrical
    })
}

fn is_exhaust_air(generator: &HeatingGenerator) -> bool {
    matches!(
        generator,
        HeatingGenerator::HeatPump {
            source: HeatPumpSource::ExhaustAir,
            ..
        }
    )
}

fn is_heat_pump(generator: &HeatingGenerator) -> bool {
    matches!(generator, HeatingGenerator::HeatPump { .. })
}

/// ISSO 82.1 p. 112 order (NTA 9.2.2.1.3, table 9.1): 1 exhaust-air heat
/// pumps, 2 other heat pumps, 3 CHP, 4 biomass, 5 external heat, 6
/// electric heating, 7 gas or oil boilers.
fn priority_class(generator: &HeatingGenerator) -> u32 {
    match generator {
        HeatingGenerator::HeatPump {
            source: HeatPumpSource::ExhaustAir,
            ..
        } => 1,
        HeatingGenerator::HeatPump { .. } => 2,
        HeatingGenerator::Chp { .. } => 3,
        HeatingGenerator::Biomass { .. } => 4,
        HeatingGenerator::DistrictHeat => 5,
        HeatingGenerator::Electric { .. } => 6,
        HeatingGenerator::Boiler { .. } | HeatingGenerator::NonePresent => 7,
    }
}

/// §9.3.2 / NTA 9.6.1: the kernel `multiple` generator with preferences
/// from the p. 112 order and the table 9.7 powers.
fn multiple_generators(
    parts: Vec<(HeatingGenerator, Option<f64>, Value)>,
    added_preferred_generator: bool,
    reference: &str,
    recorder: &mut Recorder,
) -> Value {
    // Table 9.7: a CHP enters with its thermal power.
    let parts: Vec<(HeatingGenerator, Option<f64>, Value)> = parts
        .into_iter()
        .map(|(generator, power, value)| {
            let power = power.or_else(|| {
                matches!(generator, HeatingGenerator::Chp { .. })
                    .then(|| value["auxiliary"]["nominalPowerKw"].as_f64())
                    .flatten()
            });
            (generator, power, value)
        })
        .collect();
    let mut classes: Vec<u32> = parts
        .iter()
        .map(|(generator, _, _)| priority_class(generator))
        .collect();
    classes.sort_unstable();
    classes.dedup();
    let known: f64 = parts
        .iter()
        .filter(|(generator, _, _)| !matches!(generator, HeatingGenerator::DistrictHeat))
        .filter_map(|(_, power, _)| *power)
        .sum();
    let mut generators = Vec::with_capacity(parts.len());
    for (index, (generator, power, value)) in parts.into_iter().enumerate() {
        let path = if index == 0 {
            "heating.nominalPowerKw".to_string()
        } else {
            format!("heating.additionalGenerators[{}].nominalPowerKw", index - 1)
        };
        let power = match power {
            Some(power) => power,
            None if matches!(generator, HeatingGenerator::DistrictHeat) && known > 0.0 => {
                // Table 9.7: external heat of unknown power delivers 50 %.
                recorder.record(
                    "external_heat_power_unknown_half",
                    &path,
                    format!("{known} kW (50 % of the total)"),
                    "ISSO 82.1 p. 113 (table 9.7)",
                );
                known
            }
            None => {
                recorder.issue("generator_power_required", path);
                0.0
            }
        };
        let preference = classes
            .iter()
            .position(|class| *class == priority_class(&generator))
            .map_or(1, |position| position + 1);
        generators.push(json!({
            "preference": preference,
            "nominalPowerKw": power,
            "generator": value,
        }));
    }
    recorder.record(
        "several_generators_preference_order",
        "heating.additionalGenerators",
        "heat pumps, CHP, biomass, external heat, electric, boilers".into(),
        "ISSO 82.1 p. 112 (§9.3.2)",
    );
    json!({
        "kind": "multiple",
        "generators": generators,
        "addedPreferredGenerator": added_preferred_generator,
        "sourceReference": format!("{reference}; ISSO 82.1 §9.3.2"),
    })
}

/// One survey generator as a kernel generator.
struct Converted {
    value: Value,
    /// The generator's auxiliary energy excludes the distribution pump.
    needs_pump: bool,
    heat_pump_renewable: Option<Value>,
}

#[allow(clippy::too_many_arguments)]
fn convert_generator(
    generator: &HeatingGenerator,
    design: DesignClass,
    hydronic: bool,
    collective: bool,
    nominal_power_kw: Option<f64>,
    id: &str,
    reference: &str,
    construction_year: i32,
    recorder: &mut Recorder,
) -> Converted {
    let mut heat_pump_renewable = None;
    let mut needs_pump = false;
    let value = match generator {
        HeatingGenerator::Boiler {
            boiler_type,
            pilot_flame,
            inside_thermal_boundary,
            manufacture_year,
            installation_year,
        } => {
            let kind = match boiler_type {
                BoilerType::Conventional => "conventional",
                BoilerType::Vr => "vr",
                BoilerType::Hr100 => "hr100",
                BoilerType::Hr104 => "hr104",
                BoilerType::Hr107 => "hr107",
                BoilerType::Hydrogen => {
                    recorder.record(
                        "hydrogen_boiler_hr107",
                        "heating.generator.boilerType",
                        "hr107".into(),
                        "ISSO 82.1 p. 108",
                    );
                    "hr107"
                }
            };
            let pilot = pilot_flame.unwrap_or_else(|| {
                recorder.record(
                    "pilot_flame_unknown_present",
                    "heating.generator.pilotFlame",
                    "true".into(),
                    "ISSO 82.1 p. 108 (table 9.3)",
                );
                true
            });
            let year = super::general::device_year(
                *manufacture_year,
                *installation_year,
                construction_year,
                recorder,
                "heating.generator",
            );
            json!({
                "kind": "gas_boiler",
                "boiler": {
                    "generatorId": id,
                    "role": if collective { "collective" } else { "individual_main" },
                    "location": if *inside_thermal_boundary { "inside_thermal_boundary" } else { "outside_thermal_boundary" },
                    "kind": kind,
                    "fuel": "natural_gas",
                    "averageDesignEmissionTemperatureC": design.mean_c(),
                    "emissionCircuit": "direct",
                    "equipmentReference": reference,
                    "locationReference": reference,
                    "temperatureAndCircuitReference": format!("{reference}; table 9.9 class {}", design.label()),
                    "pilotFlamePresent": pilot,
                    "installationYear": year,
                    "installationYearReference": "basisopname (ISSO 82.1 p. 28)",
                }
            })
        }
        HeatingGenerator::HeatPump {
            source,
            air_sink,
            capacity_kw,
            source_regeneration_factor,
            high_efficiency_evidence,
            ..
        } => {
            let table_source = match source {
                HeatPumpSource::OutdoorAir => "outdoor_air",
                HeatPumpSource::ExhaustAir => "exhaust_air",
                HeatPumpSource::OutdoorAndExhaustAir => {
                    recorder.record(
                        "combined_air_source_outdoor_row",
                        "heating.generator.source",
                        "outdoor_air".into(),
                        "NTA table 9.27 footnote c; ISSO 82.1 WD p. 43–45",
                    );
                    "outdoor_air"
                }
                HeatPumpSource::Ground => "ground",
                HeatPumpSource::Groundwater => "groundwater_below15_c",
                HeatPumpSource::SurfaceWater => {
                    recorder.record(
                        "individual_surface_water_as_ground",
                        "heating.generator.source",
                        "ground".into(),
                        "ISSO 82.1 p. 111",
                    );
                    "ground"
                }
                HeatPumpSource::WaterBasedUnknown => {
                    recorder.record(
                        "heat_pump_water_source_unknown_ground",
                        "heating.generator.source",
                        "ground".into(),
                        "ISSO 82.1 p. 110 (table 9.6)",
                    );
                    "ground"
                }
            };
            let ground_row = matches!(table_source, "ground" | "groundwater_below15_c");
            let (correction, correction_reference) = if ground_row && !*air_sink {
                match source_regeneration_factor {
                    Some(factor) => (json!(factor), json!(format!("{reference}; annex V"))),
                    None => {
                        recorder.record(
                            "source_regeneration_none_c_source_1",
                            "heating.generator.sourceRegenerationFactor",
                            "1.0".into(),
                            "ISSO 82.1 p. 110; NTA table 9.27 footnote a",
                        );
                        (
                            json!(1.0),
                            json!("NTA 8800 table 9.27 footnote a: no regeneration"),
                        )
                    }
                }
            } else {
                if source_regeneration_factor.is_some() {
                    recorder.issue(
                        "source_regeneration_not_applicable",
                        "heating.generator.sourceRegenerationFactor",
                    );
                }
                (Value::Null, Value::Null)
            };
            let exhaust = matches!(source, HeatPumpSource::ExhaustAir);
            heat_pump_renewable = Some(json!({
                "sourceBelow20C": true,
                "exhaustAirSource": exhaust,
                "combinedOutdoorAndExhaustAir": matches!(source, HeatPumpSource::OutdoorAndExhaustAir),
                "sourceReference": reference,
            }));
            let mut forfait = json!({
                "generatorId": id,
                "classificationSourceReference": reference,
                "scope": "residential_at_most25_kw",
                "source": table_source,
                "sink": if *air_sink { "indoor_air" } else { "hydronic" },
                "designSupplyTemperatureC": design.supply_c(),
                "sourceCorrectionFactor": correction,
                "sourceCorrectionReference": correction_reference,
                "collectiveBuildingInstallation": collective,
            });
            if let Some(capacity) = capacity_kw {
                forfait["thermalCapacityKw"] = json!(capacity);
                forfait["capacitySourceReference"] = json!(reference);
            }
            if let Some(evidence) = high_efficiency_evidence {
                forfait["rowVariant"] = json!("table_9_28_high_efficiency");
                forfait["highEfficiencyEvidence"] = evidence.clone();
            }
            json!({
                "kind": "heat_pump_forfait",
                "forfait": forfait,
                "sourceSystem": "individual",
                "sourceSystemReference": reference,
            })
        }
        HeatingGenerator::DistrictHeat => {
            needs_pump = hydronic;
            json!({
                "kind": "external_heat",
                "supplierReference": reference,
                "qualityDeclarationPresent": false,
                "auxiliary": {"electricallyConnectedDevices": 1, "sourceReference": "basisopname: one delivery set"},
            })
        }
        HeatingGenerator::Electric { connected_devices } => {
            needs_pump = hydronic;
            json!({
                "kind": "electric_resistance",
                "equipmentReference": reference,
                "auxiliary": {"electricallyConnectedDevices": connected_devices, "sourceReference": reference},
            })
        }
        HeatingGenerator::Biomass {
            appliance,
            inside_thermal_boundary,
            sole_heating_in_served_rooms,
            annex_r_compliant,
        } => {
            needs_pump = hydronic;
            let compliant = annex_r_compliant.unwrap_or_else(|| {
                recorder.record(
                    "biomass_annex_r_unknown_not_compliant",
                    "heating.generator.annexRCompliant",
                    "false".into(),
                    "ISSO 82.1 p. 111–112, p. 28",
                );
                false
            });
            let appliance = match appliance {
                BiomassApplianceAnswer::FreestandingWoodStove => "freestanding_wood_stove",
                BiomassApplianceAnswer::InsertStove => "insert_stove",
                BiomassApplianceAnswer::PelletStove => "pellet_stove",
                BiomassApplianceAnswer::AccumulatingStove => "accumulating_stove",
                BiomassApplianceAnswer::CentralBoiler => "central_boiler",
            };
            json!({
                "kind": "biomass",
                "appliance": appliance,
                "location": if *inside_thermal_boundary { "inside_thermal_boundary" } else { "outside_thermal_boundary" },
                "annexRCompliantAtMost500Kw": compliant,
                "annexRReference": reference,
                "equipmentReference": reference,
                "soleHeatingInServedRooms": sole_heating_in_served_rooms,
                "auxiliary": {"electricallyConnectedDevices": 1, "sourceReference": reference},
            })
        }
        HeatingGenerator::Chp {
            electrical_power_kw,
            thermal_power_kw,
            engine,
            manufacture_year,
            hre_declared,
            low_temperature,
        } => {
            needs_pump = hydronic;
            let year = super::general::device_year(
                *manufacture_year,
                None,
                construction_year,
                recorder,
                "heating.generator",
            );
            let thermal =
                chp_thermal_power(*electrical_power_kw, *thermal_power_kw, *engine, recorder);
            json!({
                "kind": "chp",
                "chp": {
                    "powerKw": electrical_power_kw,
                    "builtAfter2006": year > 2006,
                    "hreDeclared": hre_declared,
                    "lowTemperature": low_temperature,
                },
                // 9.6.8.2 (9.91) with the thermal power as burner power.
                "auxiliary": {"electricallyConnectedDevices": 1, "nominalPowerKw": thermal, "sourceReference": reference},
                "equipmentReference": reference,
            })
        }
        HeatingGenerator::NonePresent => unreachable!("replaced by the caller"),
    };
    let mut value = value;
    if collective {
        // A collective boiler or heat pump: its auxiliary energy (9.91)
        // excludes the distribution pump; a collective boiler needs its
        // nominal power (table 9.7).
        match value["kind"].as_str() {
            Some("gas_boiler") => {
                if nominal_power_kw.is_none() {
                    recorder.issue(
                        "collective_generator_power_required",
                        "heating.nominalPowerKw",
                    );
                }
                value["auxiliary"] = json!({
                    "electricallyConnectedDevices": 1,
                    "nominalPowerKw": nominal_power_kw,
                    "sourceReference": reference,
                });
                needs_pump = hydronic;
            }
            Some("heat_pump_forfait") => needs_pump = hydronic,
            _ => {}
        }
    }
    Converted {
        value,
        needs_pump,
        heat_pump_renewable,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn heating(generator: HeatingGenerator, emitters: Emitters) -> SurveyHeating {
        SurveyHeating {
            generator,
            emitters,
            design_class: None,
            heat_pump_above_70_declaration: None,
            balanced: None,
            control: ControlAnswer::Unknown,
            unheated_pipes: None,
            storeys: 2,
            nominal_power_kw: None,
            additional_generators: Vec::new(),
            added_preferred_generator: false,
            collective: None,
            air_heating: None,
            source_reference: "survey".into(),
        }
    }

    #[test]
    fn air_heating_maps_table_9_16_to_air_heaters() {
        let mut recorder = Recorder::default();
        let mut survey = heating(HeatingGenerator::NonePresent, Emitters::AirHeating);
        survey.air_heating = Some(AirHeatingAnswer::Direct {
            radial_fan: None,
            count: Some(3),
        });
        let derived = derive_heating(&survey, 1990, &mut recorder);
        assert_eq!(derived.emission["airHeaters"]["kind"]["kind"], "direct");
        assert!(derived.emission["airHeaters"]["kind"]["radialFan"].is_null());
        assert!(recorder
            .applied
            .iter()
            .any(|item| item.rule == "air_heater_fan_unknown_radial"));

        let mut recorder = Recorder::default();
        survey.air_heating = Some(AirHeatingAnswer::Indirect {
            room_height_above_8_m: Some(false),
            warm_air_return: Some(true),
            ec_motor: Some(true),
            count: None,
        });
        let derived = derive_heating(&survey, 1990, &mut recorder);
        let heaters = &derived.emission["airHeaters"]["kind"];
        assert_eq!(heaters["kind"], "indirect");
        assert_eq!(heaters["ecMotor"], true);
        assert!(recorder
            .applied
            .iter()
            .all(|item| !item.rule.starts_with("air_heater")));

        // Via the AHU: no air-heater fans; unknown type: not applicable.
        survey.air_heating = Some(AirHeatingAnswer::ViaAirHandlingUnit);
        let derived = derive_heating(&survey, 1990, &mut recorder);
        assert!(derived.emission.get("airHeaters").is_none());
        survey.air_heating = None;
        let mut recorder = Recorder::default();
        derive_heating(&survey, 1990, &mut recorder);
        assert!(recorder
            .applied
            .iter()
            .any(|item| item.rule == "air_heating_type_unknown"));

        // An air-heating answer with other emitters is inconsistent.
        let mut recorder = Recorder::default();
        let mut radiators = heating(HeatingGenerator::NonePresent, Emitters::Radiators);
        radiators.air_heating = Some(AirHeatingAnswer::ViaAirHandlingUnit);
        derive_heating(&radiators, 1990, &mut recorder);
        assert_eq!(
            recorder.issues[0].code,
            "air_heating_requires_air_heating_emitters"
        );
    }

    #[test]
    fn missing_generator_is_a_conventional_boiler_with_pilot_flame() {
        let mut recorder = Recorder::default();
        let derived = derive_heating(
            &heating(HeatingGenerator::NonePresent, Emitters::Radiators),
            1960,
            &mut recorder,
        );
        assert_eq!(derived.generator["boiler"]["kind"], "conventional");
        assert_eq!(derived.generator["boiler"]["pilotFlamePresent"], true);
        assert_eq!(derived.generator["boiler"]["installationYear"], 1960);
        assert_eq!(
            derived.generator["boiler"]["averageDesignEmissionTemperatureC"],
            80.0
        );
        assert_eq!(derived.emission["balancing"], "none_or_unknown");
        assert_eq!(derived.emission["control"], "other_or_unknown");
        assert!(derived.distribution_system.is_none());
    }

    #[test]
    fn design_class_follows_table_9_9() {
        let mut recorder = Recorder::default();
        let hp = HeatingGenerator::HeatPump {
            source: HeatPumpSource::WaterBasedUnknown,
            air_sink: false,
            high_temperature: false,
            capacity_kw: Some(6.0),
            source_regeneration_factor: None,
            high_efficiency_evidence: None,
        };
        assert_eq!(
            design_class(Emitters::FloorHeating, &hp, &mut recorder),
            DesignClass::C45_40
        );
        assert_eq!(
            design_class(Emitters::Radiators, &hp, &mut recorder),
            DesignClass::C55_47
        );
        let derived = derive_heating(&heating(hp, Emitters::Radiators), 2015, &mut recorder);
        assert_eq!(derived.generator["forfait"]["source"], "ground");
        assert_eq!(
            derived.generator["forfait"]["designSupplyTemperatureC"],
            55.0
        );
        assert!(derived.heat_pump_renewable.is_some());
        // p. 110: no solar regeneration, c_source 1,0.
        assert_eq!(derived.generator["forfait"]["sourceCorrectionFactor"], 1.0);
    }

    #[test]
    fn heat_pump_above_70_needs_a_controlled_declaration() {
        // Erratum §4 on table 9.9 footnotes 9–11.
        let hp: HeatingGenerator = serde_json::from_value(json!({
            "kind": "heat_pump",
            "source": "water_based_unknown",
            "highTemperature": true,
        }))
        .unwrap();
        let mut survey = heating(hp, Emitters::Radiators);
        survey.design_class = Some(DesignClass::C90_70);
        let mut recorder = Recorder::default();
        derive_heating(&survey, 2015, &mut recorder);
        assert!(recorder
            .issues
            .iter()
            .any(|item| item.code == "heat_pump_above_70_requires_declaration"));
        survey.heat_pump_above_70_declaration = Some("BCRG verklaring 123".into());
        let mut recorder = Recorder::default();
        derive_heating(&survey, 2015, &mut recorder);
        assert!(recorder.issues.is_empty());
        // 70/50 is not above 70 °C.
        survey.heat_pump_above_70_declaration = None;
        survey.design_class = Some(DesignClass::C70_50);
        let mut recorder = Recorder::default();
        derive_heating(&survey, 2015, &mut recorder);
        assert!(recorder.issues.is_empty());
        // A boiler at 90/70 needs no declaration.
        let mut boiler = heating(HeatingGenerator::NonePresent, Emitters::Radiators);
        boiler.design_class = Some(DesignClass::C90_70);
        let mut recorder = Recorder::default();
        derive_heating(&boiler, 2015, &mut recorder);
        assert!(recorder.issues.is_empty());
    }

    #[test]
    fn exhaust_air_heat_pump_needs_a_second_generator() {
        let mut recorder = Recorder::default();
        let hp = HeatingGenerator::HeatPump {
            source: HeatPumpSource::ExhaustAir,
            air_sink: false,
            high_temperature: false,
            capacity_kw: None,
            source_regeneration_factor: None,
            high_efficiency_evidence: None,
        };
        let derived = derive_heating(&heating(hp, Emitters::Radiators), 2015, &mut recorder);
        assert_eq!(
            derived.generator["forfait"]["sourceCorrectionFactor"],
            Value::Null
        );
        assert_eq!(
            recorder.issues[0].code,
            "exhaust_air_heat_pump_second_generator_required"
        );
    }

    #[test]
    fn biomass_annex_r_unknown_is_not_compliant() {
        let mut recorder = Recorder::default();
        let stove = HeatingGenerator::Biomass {
            appliance: BiomassApplianceAnswer::PelletStove,
            inside_thermal_boundary: true,
            sole_heating_in_served_rooms: true,
            annex_r_compliant: None,
        };
        let derived = derive_heating(&heating(stove, Emitters::LocalHeaters), 2010, &mut recorder);
        assert_eq!(derived.generator["annexRCompliantAtMost500Kw"], false);
    }

    #[test]
    fn district_heat_with_radiators_gets_a_forfait_pump() {
        let mut recorder = Recorder::default();
        let derived = derive_heating(
            &heating(HeatingGenerator::DistrictHeat, Emitters::Radiators),
            1975,
            &mut recorder,
        );
        let system = derived.distribution_system.unwrap();
        assert_eq!(system["pump"]["heatMeterPresent"], false);
        assert_eq!(system["designTemperatureClass"], "90_70");
    }
}
