/**
 * Dutch names of the kernel input fields for the input overview of the report
 * (feedback 9 Oct 2026: "demand uses fixed c1 ventilatie" is no Dutch). One
 * name per field, with its unit; the path still shows the field itself.
 */
export const INPUT_KEY_LABELS: Record<string, string> = {
  activeCooling: 'actieve koeling',
  actualPipeLengthM: 'werkelijke leidinglengte [m]',
  airHandlingUnit: 'luchtbehandelingskast',
  apartmentBuilding: 'woongebouw',
  appliance: 'toestel',
  areaElectricity: 'oppervlak elektriciteit',
  areaM2: 'oppervlak [m²]',
  areaSourceReference: 'bron oppervlak',
  areas: 'oppervlakken',
  averageDesignEmissionTemperatureC: 'gemiddelde ontwerpafgiftetemperatuur [°C]',
  azimuthDeg: 'azimut [°]',
  bacsFactor: 'BACS-factor',
  bacsSourceReference: 'bron BACS',
  balancing: 'waterzijdige inregeling',
  bathroomLengthM: 'leidinglengte badkamer [m]',
  batteryStoragePresent: 'batterijopslag aanwezig',
  bblFunction: 'gebruiksfunctie (Bbl)',
  below: 'onder de vloer',
  boiler: 'ketel',
  boilingWaterTap: 'kokendwaterkraan',
  bufferVessel: 'buffervat',
  buildingHeightM: 'gebouwhoogte [m]',
  buildingType: 'gebouwtype',
  bypass: 'bypass',
  calculationScope: 'rekenomvang',
  category: 'categorie',
  ceiling: 'plafond',
  centralOnControl: 'centrale aan/uit-regeling',
  circulation: 'circulatieleiding',
  coldRecoveryEvidence: 'bewijs koudeterugwinning',
  collective: 'collectief',
  collectiveHeatPumpSource: 'collectieve warmtepompbron',
  collectiveHotWaterDeliverySet: 'collectieve afleverset warm water',
  combustionAppliances: 'verbrandingstoestellen',
  connectedStoreys: 'aangesloten bouwlagen',
  connectionFactor: 'aansluitfactor',
  constantVolumeControl: 'constant-volumeregeling',
  constructionResistanceM2kPerW: 'warmteweerstand constructie [m²K/W]',
  constructionYear: 'bouwjaar',
  control: 'regeling',
  cooling: 'koeling',
  coolingC: 'koelen [°C]',
  coolingSetpointC: 'setpoint koelen [°C]',
  current: 'huidig',
  daylight: 'daglicht',
  declared: 'verklaard',
  declaredRenewableHeat: 'verklaarde hernieuwbare warmte',
  declaredUses: 'verklaarde toepassingen',
  deliverySets: 'afleversets',
  demand: 'behoefte',
  demandUsesFixedC1Ventilation: 'behoefte met vast ventilatiesysteem C1',
  depthClass: 'diepteklasse',
  designTemperatureClass: 'ontwerptemperatuurklasse',
  direct: 'direct naar buiten',
  distribution: 'distributie',
  distributionSystem: 'distributiesysteem',
  ducts: 'kanalen',
  dwellingCount: 'aantal woningen',
  dwellingType: 'woningtype',
  edgeInsulation: 'randisolatie',
  edgeThermalBridges: 'randthermische bruggen',
  efficiency: 'rendement',
  elements: 'elementen',
  emission: 'afgifte',
  emissionCircuit: 'afgiftecircuit',
  equipmentReference: 'productverwijzing',
  evidenceReference: 'bewijsverwijzing',
  exchanger: 'warmtewisselaar',
  exposedPerimeterM: 'blootgestelde omtrek [m]',
  externalSupply: 'externe levering',
  extractedLuminaires: 'afgezogen armaturen',
  fans: 'ventilatoren',
  floor: 'vloer',
  floorAboveCrawlspace: 'vloer boven kruipruimte',
  floorResistanceM2kPerW: 'warmteweerstand vloer [m²K/W]',
  flowControlPercent: 'debietregeling [%]',
  flowReduction: 'debietreductie',
  forfaitDeltaUWPerM2k: 'forfaitaire toeslag ΔU_for [W/m²K]',
  frameFraction: 'kozijnfractie',
  fuel: 'brandstof',
  function: 'functie',
  functions: 'functies',
  gPerpendicular: 'g-waarde loodrecht',
  generator: 'opwekker',
  generatorId: 'opwekker',
  grillePreheating: 'voorverwarming roosters',
  groundFloors: 'vloeren op grond',
  groundInventoryConfirmed: 'grondgebonden inventaris bevestigd',
  heatPumpRenewable: 'hernieuwbaar warmtepomp',
  heatRecovery: 'warmteterugwinning',
  heating: 'verwarming',
  heatingC: 'verwarmen [°C]',
  heatingLimitExtraKwh: 'extra grenswaarde verwarming [kWh]',
  heatingSetpointC: 'setpoint verwarmen [°C]',
  hotWater: 'warm tapwater',
  hotWaterRecoverableKwh: 'terugwinbaar warm tapwater [kWh]',
  id: 'id',
  inHeatedZone: 'binnen verwarmde zone',
  infiltration: 'infiltratie',
  installation: 'installatie',
  installationYear: 'installatiejaar',
  installationYearReference: 'bron installatiejaar',
  installedCapacity: 'geïnstalleerd vermogen',
  insulated: 'geïsoleerd',
  insulation: 'isolatie',
  internalGains: 'interne warmtelast',
  kind: 'soort',
  kitchenLengthM: 'leidinglengte keuken [m]',
  kitchenOnly: 'alleen keuken',
  labelFunction: 'labelfunctie',
  largeOfficeGroup: 'grote kantoorgroep',
  layout: 'opstelling',
  ledFrom2017: 'led vanaf 2017',
  lighting: 'verlichting',
  lightingZones: 'verlichtingszones',
  linearBridges: 'lineaire thermische bruggen',
  location: 'plaats',
  locationReference: 'bron plaats',
  loss: 'verlies',
  lossAreaM2: 'verliesoppervlak [m²]',
  lossAreaSourceReference: 'bron verliesoppervlak',
  manufactureYear: 'bouwjaar toestel',
  maximumCapacityForCooling: 'maximaal vermogen voor koeling',
  meanLengthM: 'gemiddelde lengte [m]',
  measuredClass: 'gemeten klasse',
  method: 'methode',
  mounting: 'montage',
  need: 'behoefte',
  normVersion: 'normversie',
  obstruction: 'belemmering',
  obstructionFactors: 'belemmeringsfactoren',
  occupancy: 'bezetting',
  onSiteProduction: 'opwekking op eigen perceel',
  opaqueElements: 'dichte delen',
  opaqueInventoryComplete: 'inventaris dichte delen compleet',
  orientation: 'oriëntatie',
  overventilation: 'overventilatie',
  panelCount: 'aantal panelen',
  panelPeakPowerW: 'piekvermogen per paneel [W]',
  parasitic: 'parasitair',
  peakPower: 'piekvermogen',
  permitApplicationAfter20260529: 'vergunningaanvraag na 29 mei 2026',
  pilotFlamePresent: 'waakvlam aanwezig',
  pipeTransmittance: 'warmteverlies leiding',
  pipesAlsoForHotWater: 'leidingen ook voor warm tapwater',
  pointBridges: 'puntvormige thermische bruggen',
  power: 'vermogen',
  producedFrom2018: 'geproduceerd vanaf 2018',
  productionInventoryComplete: 'inventaris opwekking compleet',
  pump: 'pomp',
  pvSystems: 'PV-systemen',
  qv10DmPerSM2: 'luchtdoorlatendheid q_v10 [dm³/s·m²]',
  recirculationPercent: 'recirculatie [%]',
  renovationYear: 'renovatiejaar',
  role: 'rol',
  served: 'bediend',
  setpoints: 'setpoints',
  sharedZones: 'gedeelde zones',
  showerHeatRecovery: 'douche-wtw',
  sourceReference: 'bron',
  spaceHeating: 'ruimteverwarming',
  state: 'toestand',
  storage: 'opslag',
  storeys: 'bouwlagen',
  supplyDuctInsulation: 'isolatie toevoerkanaal',
  supplyDuctLengthM: 'lengte toevoerkanaal [m]',
  swimmingPool: 'zwembad',
  system: 'systeem',
  temperatureAndCircuitReference: 'bron temperatuur en circuit',
  thermalMass: 'thermische massa',
  tiltDeg: 'helling [°]',
  totalUsableFloorAreaM2: 'totale gebruiksoppervlakte A_g [m²]',
  transmission: 'transmissie',
  uValueWPerM2k: 'U-waarde [W/m²K]',
  unheated: 'onverwarmde ruimten',
  unheatedAmbientC: 'temperatuur onverwarmde ruimte [°C]',
  unheatedPipeLengthM: 'leidinglengte in onverwarmde ruimte [m]',
  unheatedPipeTransmittance: 'warmteverlies leiding in onverwarmde ruimte',
  unheatedReductionFactor: 'reductiefactor onverwarmde ruimte',
  unit: 'eenheid',
  usableFloorAreaM2: 'gebruiksoppervlakte A_g [m²]',
  usageFunction: 'gebruiksfunctie',
  useInventoryComplete: 'inventaris gebruik compleet',
  valvesInsulated: 'afsluiters geïsoleerd',
  variant: 'variant',
  ventilation: 'ventilatie',
  ventilationFlows: 'ventilatiedebieten',
  ventilationOpeningM2PerM: 'ventilatieopening [m²/m]',
  ventilativeCooling: 'ventilatieve koeling',
  verticalPipes: 'verticale leidingen',
  volumeL: 'volume [l]',
  wall: 'wand',
  wallResistanceM2kPerW: 'warmteweerstand wand [m²K/W]',
  wallUValueWPerM2k: 'U-waarde wand [W/m²K]',
  wholeDwellingAreaM2: 'oppervlak hele woning [m²]',
  windowInventoryComplete: 'inventaris ramen compleet',
  windows: 'ramen',
  zoneId: 'rekenzone',
};
